/*^ The MIT License
 * 
 * Copyright 2022 Studio 42 GmbH ( https://www.s42m.de ).
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

require "dl:standard/base.dl";

dynamic type User {
	
	String name /*@length(4, 120)*/ : "Default";
	UUID id /*@generateUUID*/ @required /*@unique*/;
}

User test1 @export {
	String name: "John \"Rambo\" Doe 1";
	UUID id: "ad232384-4a04-4119-9e95-4753f31e3b09";
	String globalName: "TEST";
}

User {
	name: "John \"Rambo\" Doe 2";
	id: "ad332384-4a04-4119-9e95-4753f31e3b09";
}

User user2 {
	String name: "John \"Rambo\" Doe 3";
	id: "ad232384-4a04-4119-9e95-4753f31e3b04";
}

User {
	name: "John \"Rambo\" Doe 4";
	id: "ad232384-4a04-4119-9e95-4753f31e3b03";
}

User {
	name: "John \"Rambo\" Doe 5";
	id: "ad232384-4a04-4119-9e95-4753f31e3b07";
}