/*^ MIT License
 *
 * This is the MIT License ...
 * ...
 * 
 */

require "dl:standard/base.dl";

annotation odd : !@even;
annotation evenRange42OrOdd : ( @range(0, 42) & @even ) | ( !@range(0, 42) & @odd );

// Special constrained base types
final type EvenLong42 @evenRange42OrOdd extends Long;

// Simple tree types
abstract type Node;
type Container extends Node contains Node alias Root;
dynamic type Leaf extends Node;
type Statistics extends Node
{
	EvenLong42 l42 @required;
	String version @required;
}

//^ Root root
Root root {
	Statistics {
		version : "1.0.0";
		l42 : 49;
	}
}
//^

boolean b : true & !(false & true);
