// Resolvment of other modules can be extended easily
require "dl:standard/base.dl";

annotation odd : !@even;
annotation odd42 : @odd & @range(0, 42);
annotation odd21to42 : @odd42 & @range(21, 42);

annotation requiredFile : @required & @isFile;

type SpecialLong @odd21to42 extends Long;

SpecialLong val : 21;

type MyType
{
	Path path @requiredFile;
}

MyType t {
	path : "/home/notes-wsbs2022.txt";
}