// Resolvment of other modules can be extended easily
require "dl:standard/base.dl";

// Need the trick with the | @noDefaultValue to support defining attributes without giving them default values
annotation odd : !@even | @noDefaultValue;
annotation odd42 : @odd & @range(0, 42);
annotation odd21to42 : @odd42 & @range(21);

annotation requiredFile : @required & @isFile;

type SpecialLong @odd21to42 extends Long;

type RequiredFile @requiredFile extends Path;

SpecialLong val : 21;

type MyType
{
	RequiredFile path;
	String display;
	SpecialLong val;
	Long val2 @odd21to42;
}

MyType t @export {
	path : "/home/notes-wsbs2022.txt";
	val : 41;
	val2 : 23;
}